module Main where

import Control.Exception
import qualified Misc.MathTest as MM (test)

main = do
 MM.test
